name: aoc
description: Solving festive puzzles with some fun!
version: 1.0.0
repository: https://github.com/Azzeccagarbugli/aoc

environment:
  sdk: ^3.10.1

dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
